/*
 * Agile.Now.AccessHub API
 *
 * Agile.Now.AccessHub is a secure REST API designed to manage accounts, access groups, user groups, organizations, locations, applications, roles, and webhooks. This API provides a robust and scalable solution for managing user access and organizational structures in a multi-tenant environment.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: dev@agilenow.io
 *
 * BSD 3-Clause License
 * 
 * Copyright (c) 2024, eSystems Nordic Ltd.
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice, this list
 *    of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice, this
 *    list of conditions and the following disclaimer in the documentation and/or other
 *    materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its contributors may be
 *    used to endorse or promote products derived from this software without specific
 *    prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Agile.Now.AccessHub.Client;
using Agile.Now.AccessHub.Api;
// uncomment below to import models
//using Agile.Now.AccessHub.Model;

namespace Agile.Now.AccessHub.Test.Api
{
    /// <summary>
    ///  Class for testing GroupExternalsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class GroupExternalsApiTests : IDisposable
    {
        private GroupExternalsApi instance;

        public GroupExternalsApiTests()
        {
            instance = new GroupExternalsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GroupExternalsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' GroupExternalsApi
            //Assert.IsType<GroupExternalsApi>(instance);
        }

        /// <summary>
        /// Test CreateGroupExternal
        /// </summary>
        [Fact]
        public void CreateGroupExternalTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GroupExternalData groupExternalData = null;
            //var response = instance.CreateGroupExternal(groupExternalData);
            //Assert.IsType<GroupExternal>(response);
        }

        /// <summary>
        /// Test DeleteGroupExternal
        /// </summary>
        [Fact]
        public void DeleteGroupExternalTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string name = null;
            //var response = instance.DeleteGroupExternal(id, name);
            //Assert.IsType<GroupExternal>(response);
        }

        /// <summary>
        /// Test DeleteGroupExternalUserExternal
        /// </summary>
        [Fact]
        public void DeleteGroupExternalUserExternalTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string subId = null;
            //string name = null;
            //string subName = null;
            //var response = instance.DeleteGroupExternalUserExternal(id, subId, name, subName);
            //Assert.IsType<UserExternal>(response);
        }

        /// <summary>
        /// Test GetGroupExternal
        /// </summary>
        [Fact]
        public void GetGroupExternalTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string name = null;
            //var response = instance.GetGroupExternal(id, name);
            //Assert.IsType<GroupExternal>(response);
        }

        /// <summary>
        /// Test ListGroupExternalUserExternals
        /// </summary>
        [Fact]
        public void ListGroupExternalUserExternalsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string name = null;
            //string fields = null;
            //string filters = null;
            //string orders = null;
            //int? currentPage = null;
            //int? pageSize = null;
            //var response = instance.ListGroupExternalUserExternals(id, name, fields, filters, orders, currentPage, pageSize);
            //Assert.IsType<UserExternals>(response);
        }

        /// <summary>
        /// Test ListGroupExternals
        /// </summary>
        [Fact]
        public void ListGroupExternalsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string fields = null;
            //string filters = null;
            //string orders = null;
            //int? currentPage = null;
            //int? pageSize = null;
            //var response = instance.ListGroupExternals(fields, filters, orders, currentPage, pageSize);
            //Assert.IsType<GroupExternals>(response);
        }

        /// <summary>
        /// Test PatchGroupExternalUserExternals
        /// </summary>
        [Fact]
        public void PatchGroupExternalUserExternalsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //UserExternalsData userExternalsData = null;
            //string name = null;
            //string deleteNotExists = null;
            //var response = instance.PatchGroupExternalUserExternals(id, userExternalsData, name, deleteNotExists);
            //Assert.IsType<UserExternals>(response);
        }

        /// <summary>
        /// Test PatchGroupExternals
        /// </summary>
        [Fact]
        public void PatchGroupExternalsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GroupExternalsData groupExternalsData = null;
            //var response = instance.PatchGroupExternals(groupExternalsData);
            //Assert.IsType<GroupExternals>(response);
        }

        /// <summary>
        /// Test UpdateGroupExternal
        /// </summary>
        [Fact]
        public void UpdateGroupExternalTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //GroupExternalData groupExternalData = null;
            //string name = null;
            //var response = instance.UpdateGroupExternal(id, groupExternalData, name);
            //Assert.IsType<GroupExternal>(response);
        }

        /// <summary>
        /// Test UpsertGroupExternal
        /// </summary>
        [Fact]
        public void UpsertGroupExternalTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GroupExternalData groupExternalData = null;
            //var response = instance.UpsertGroupExternal(groupExternalData);
            //Assert.IsType<GroupExternal>(response);
        }

        /// <summary>
        /// Test UpsertGroupExternalUserExternal
        /// </summary>
        [Fact]
        public void UpsertGroupExternalUserExternalTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //UserExternalData userExternalData = null;
            //string name = null;
            //var response = instance.UpsertGroupExternalUserExternal(id, userExternalData, name);
            //Assert.IsType<UserExternal>(response);
        }
    }
}
